In [36]:
# importing important pacakages
import pandas as pd
import numpy as np
import mysql.connector
import requests

In [37]:
#! pip install mysql-connector-python

In [38]:
#%pip uninstall mysql-connector

In [39]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="root"
)

mycursor = mydb.cursor()
# mycursor.execute("CREATE DATABASE IF NOT EXISTS cats_db")

In [40]:
# Loading
def fetch_data(url):
  response = requests.get(url)
  data = response.json()
  return data

url = 'https://api.thecatapi.com/v1/breeds'
data = fetch_data(url)

In [43]:
## changing the data to dataframe
df = pd.DataFrame(data)

In [44]:
averages = []
for life_span in df['life_span']:
    lowest, highest = life_span.split(' - ')
    average = (int(lowest) + int(highest)) / 2
    averages.append(average)

df['life_span'] = averages

In [45]:
df

,weight,id,name,breed_group,cfa_url,vetstreet_url,vcahospitals_url,temperament,origin,country_codes,...,natural,rare,rex,suppressed_tail,short_legs,wikipedia_url,hypoallergenic,reference_image_id,cat_friendly,bidability
0,"{'imperial': '7 - 10', 'metric': '3 - 5'}",abys,Abyssinian,None,http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx,http://www.vetstreet.com/cats/abyssinian,https://vcahospitals.com/know-your-pet/cat-bre...,"Active, Energetic, Independent, Intelligent, G...",Egypt,EG,...,1,0,0,0,0,https://en.wikipedia.org/wiki/Abyssinian_(cat),0,0XYvRd7oD,NaN,NaN
1,"{'imperial': '7 - 10', 'metric': '3 - 5'}",aege,Aegean,None,NaN,http://www.vetstreet.com/cats/aegean-cat,NaN,"Affectionate, Social, Intelligent, Playful, Ac...",Greece,GR,...,0,0,0,0,0,https://en.wikipedia.org/wiki/Aegean_cat,0,ozEvzdVM-,NaN,NaN
2,"{'imperial': '7 - 16', 'metric': '3 - 7'}",abob,American Bobtail,None,http://cfa.org/Breeds/BreedsAB/AmericanBobtail...,http://www.vetstreet.com/cats/american-bobtail,https://vcahospitals.com/know-your-pet/cat-bre...,"Intelligent, Interactive, Lively, Playful, Sen...",United States,US,...,0,0,0,1,0,https://en.wikipedia.org/wiki/American_Bobtail,0,hBXicehMA,NaN,NaN
3,"{'imperial': '5 - 10', 'metric': '2 - 5'}",acur,American Curl,None,http://cfa.org/Breeds/BreedsAB/AmericanCurl.aspx,http://www.vetstreet.com/cats/american-curl,https://vcahospitals.com/know-your-pet/cat-bre...,"Affectionate, Curious, Intelligent, Interactiv...",United States,US,...,0,0,0,0,0,https://en.wikipedia.org/wiki/American_Curl,0,xnsqonbjW,NaN,NaN
4,"{'imperial': '8 - 15', 'metric': '4 - 7'}",asho,American Shorthair,None,http://cfa.org/Breeds/BreedsAB/AmericanShortha...,http://www.vetstreet.com/cats/american-shorthair,https://vcahospitals.com/know-your-pet/cat-bre...,"Active, Curious, Easy Going, Playful, Calm",United States,US,...,1,0,0,0,0,https://en.wikipedia.org/wiki/American_Shorthair,0,JFPROfGtQ,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,"{'imperial': '6 - 12', 'metric': '3 - 5'}",tonk,Tonkinese,None,http://cfa.org/Breeds/BreedsSthruT/Tonkinese.aspx,http://www.vetstreet.com/cats/tonkinese,https://vcahospitals.com/know-your-pet/cat-bre...,"Curious, Intelligent, Social, Lively, Outgoing...",Canada,CA,...,0,0,0,0,0,https://en.wikipedia.org/wiki/Tonkinese_(cat),0,KBroiVNCM,NaN,NaN
63,"{'imperial': '7 - 15', 'metric': '3 - 7'}",toyg,Toyger,None,NaN,http://www.vetstreet.com/cats/toyger,NaN,"Playful, Social, Intelligent",United States,US,...,0,0,0,0,0,https://en.wikipedia.org/wiki/Toyger,0,O3F3_S1XN,NaN,NaN
64,"{'imperial': '5 - 10', 'metric': '2 - 5'}",tang,Turkish Angora,None,http://cfa.org/Breeds/BreedsSthruT/TurkishAngo...,http://www.vetstreet.com/cats/turkish-angora,https://vcahospitals.com/know-your-pet/cat-bre...,"Affectionate, Agile, Clever, Gentle, Intellige...",Turkey,TR,...,1,0,0,0,0,https://en.wikipedia.org/wiki/Turkish_Angora,0,7CGV6WVXq,NaN,NaN
65,"{'imperial': '7 - 20', 'metric': '3 - 9'}",tvan,Turkish Van,None,http://cfa.org/Breeds/BreedsSthruT/TurkishVan....,http://www.vetstreet.com/cats/turkish-van,https://vcahospitals.com/know-your-pet/cat-bre...,"Agile, Intelligent, Loyal, Playful, Energetic",Turkey,TR,...,1,0,0,0,0,https://en.wikipedia.org/wiki/Turkish_Van,0,sxIXJax6h,NaN,NaN
66,"{'imperial': '12 - 18', 'metric': '5 - 8'}",ycho,York Chocolate,None,NaN,NaN,NaN,"Playful, Social, Intelligent, Curious, Friendly",United States,US,...,0,0,0,0,0,https://en.wikipedia.org/wiki/York_Chocolate,0,0SxW2SQ_S,NaN,NaN

In [48]:
weights = []
for weight in df['weight']:
    lowest, highest = weight['metric'].split(' - ')
    average = (int(lowest) + int(highest)) / 2
    weights.append(average)
print(weights)

df['weight'] = weights

[4.0, 4.0, 5.0, 3.5, 5.5, 5.5, 5.5, 5.0, 3.5, 3.0, 5.0, 5.0, 4.0, 6.0, 7.0, 4.0, 4.5, 6.0, 4.0, 5.0, 5.0, 5.5, 3.5, 3.0, 5.0, 5.5, 3.5, 5.5, 5.0, 4.5, 4.5, 4.5, 4.0, 4.5, 3.5, 3.5, 5.0, 4.0, 5.5, 4.0, 6.5, 4.5, 4.5, 3.0, 4.0, 5.5, 5.0, 3.5, 5.0, 6.0, 6.5, 7.0, 3.5, 7.5, 3.5, 5.0, 5.5, 5.5, 3.0, 4.0, 4.0, 4.0, 4.0, 5.0, 3.5, 6.0, 6.5]

In [56]:
import math
urls = []
for id in df['reference_image_id']:
    if isinstance(id, float) and math.isnan(id):
        url = ""
        urls.append(url)
    else:
        url =  f"https://cdn2.thecatapi.com/images/{id}.jpg"
        urls.append(url)
df['image_url']= urls

In [57]:
df_minfied_cats = df[['id','name',  'origin', 'life_span', 'weight', 'description','image_url']]

In [58]:
df_minfied_cats[df_minfied_cats['image_url'] == '']

,id,name,origin,life_span,weight,description,image_url
30,ebur,European Burmese,Burma,12.5,4.5,"The European Burmese is a very affectionate, i...",
41,mala,Malayan,United Kingdom,15.0,4.5,Malayans love to explore and even enjoy travel...,

In [65]:
df_minfied_cats.iloc[30, 6] = 'https://platopettreats.com/cdn/shop/articles/the-rare-european-burmese-a-study-in-solid-strength_20251227011103_20251227_87dbe0dc-59ab-4fdd-8427-2fea3d1f84c0.jpg?v=1770567066&width=1080'
df_minfied_cats.iloc[41, 6] = 'https://cdn.shopify.com/s/files/1/0435/0466/4732/files/asian_cat_food_1_600x600.jpg?v=1648709012'

In [68]:
df_minfied_cats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           67 non-null     object
 1   name         67 non-null     object
 2   origin       67 non-null     object
 3   life_span    67 non-null     float64
 4   weight       67 non-null     float64
 5   description  67 non-null     object
 6   image_url    67 non-null     object
dtypes: float64(2), object(5)
memory usage: 3.8+ KB

In [ ]:
import json
data = json.loads(df_minfied_cat.to_json(orient="records"))
with open('./cats.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)